### ISSUE TITLE
BigDL version

### ISSUE THREAD

**Issue by cmusjtuliuyuan** [intel/BigDL-Tutorials#5]
[BigDL 0.1.0](https://repo1.maven.org/maven2/com/intel/analytics/bigdl/dist-spark-2.1.0-scala-2.11.8-linux64/0.1.0/dist-spark-2.1.0-scala-2.11.8-linux64-0.1.0-dist.zip)  in the intel-analytics/BigDL repo is different from the [BigDL](https://drive.google.com/file/d/0B7WbKES2D6AxZkEwNVpsMFNVVlU/view) provided in the intel-analytics/BigDL-Tutorials repo.

So when I use the BigDL in the intel-analytics/BigDL repo, there are some problems in start_notebook.sh line 17 && 18 && 19: 
Because, there is no "bigdl-SPARK_2.1-0.1.0-jar-with-dependencies.jar" in the intel-analytics/BigDL repo.
It should be changed to "bigdl-0.1.0-jar-with-dependencies.jar"

**Comment by cmusjtuliuyuan** [comment]
When I use the BigDL provided in the intel-analytics/BigDL-Tutorials repo, the [forward_and_backward.ipynb](https://github.com/intel-analytics/BigDL-Tutorials/blob/master/notebooks/neural_networks/forward_and_backward.ipynb) works well.

But when I use the BigDL 0.1.0 in the intel-analytics/BigDL, it gives me the following error.
![version_issue](https://cloud.githubusercontent.com/assets/24871871/26142985/8806e1e2-3b15-11e7-9fa1-9e0446baf33b.png)

**Comment by yangw1234** [comment]
For the first question, you should use the download link in the README page (which contains the jar with the right name)
