### ISSUE TITLE
does bigDL supports Asynchronous SGD and Synchronous SGD ? if supports please send reference link or Use case..

### ISSUE THREAD

**Issue by orsushiva** [intel/BigDL-Tutorials#64]
I want to achieve Parallel SGD on a Distributed environment on (YARN cluster).

**Comment by jason-dai** [comment]
BigDL provides data-parallel synchronous SGD; you may refer to the paper https://arxiv.org/abs/1804.05839 for more technical details.

**Comment by orsushiva** [comment]
Hey Jason, Thanks for your support, But I need coding use case on Asynchronous SGD.

**Comment by orsushiva** [comment]
If I want to implement **Parallel Sgd** on the **YARN cluster** using "**Analytics Zoo**" or "**BigDL**" which library or framework is better to Use.
